// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:652db172-bc54-40d3-9f20-34bf70c30e63",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_mlAaxMY5Q",
    "aws_user_pools_web_client_id": "3gqctk43c6r0tb4dass3sbi9ol",
    "aws_cloud_logic_custom": [
        {
            "name": "api6342d95d",
            "endpoint": "https://m5qrbjtcnf.execute-api.us-east-1.amazonaws.com/Prod",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
