// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_MiMZAdwAW",
    "aws_user_pools_web_client_id": "3q76jr1uabbgqmh474p7rbproi",
    "aws_cloud_logic_custom": [
        {
            "name": "apib6ed35cf",
            "endpoint": "https://eayr7769r5.execute-api.us-east-1.amazonaws.com/Prod",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
